apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ app }}
  namespace: {{ namespace }}
  labels:
    team: {{ team }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  image: {{ image }}
  port: 8080
  accessPolicy:
    inbound:
      rules:
        - application: bulk-frontend
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: isalive
    timeout: 10
    failureThreshold: 30
  readiness:
    initialDelay: 30
    path: isready
    timeout: 10
    failureThreshold: 30
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
        claims:
          groups:
          {{#each groups as |group|}}
            - {{ group }}
          {{/each}}

  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"

  ingresses:
    - https://bulk-backend.dev.intern.nav.no