apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bulk-backend
  namespace: team-bulk
  labels:
    team: team-bulk
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{ image }}
  port: 8080
  accesPolicy:
      inbound:
        rules:
          - application: bulk-frontend
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /metrics

  ingresses:
    - https://team-bulk.dev.intern.nav.no