apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bulk-backend
  namespace: team-bulk
  labels:
    team: team-bulk
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  image: {{ image }}
  port: 8080
  accessPolicy:
    inbound:
      rules:
        - application: bulk-frontend
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  env:
    - name: FRONTEND_CLIENT_ID
      value: 6117bfb9-e769-4d9f-a3e0-
  resources:
    limits:
      memory: "1024Mi"

  ingresses:
    - https://bulk-backend.dev.intern.nav.no